// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models.Data;

namespace Server.Migrations.UserMigrations
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20210504150157_initialusers")]
    partial class initialusers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_Id = 1,
                            Login = "Login1",
                            Password = "password",
                            User_Name = "Арбузов Арбуз Арбузович",
                            user_token = ""
                        },
                        new
                        {
                            User_Id = 2,
                            Login = "Login2",
                            Password = "qwerty",
                            User_Name = "Дынев Дынь Дыньевич",
                            user_token = ""
                        },
                        new
                        {
                            User_Id = 3,
                            Login = "Login3",
                            Password = "podsolnuh",
                            User_Name = "Кивиев Кивь Кивиевич",
                            user_token = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
